speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: null
  blank_at_zero: False
  beam_width: 500
  lm_config:
    model_path: null
    alpha: 2.0
    beta: 1.0

model_config:
  name: deepspeech2
  conv_type: conv2d
  conv_kernels: [[11, 41], [11, 21], [11, 11]]
  conv_strides: [[2, 2], [1, 2], [1, 2]]
  conv_filters: [32, 32, 96]
  conv_dropout: 0.1
  rnn_nlayers: 5
  rnn_type: lstm
  rnn_units: 512
  rnn_bidirectional: True
  rnn_rowconv: 0
  rnn_dropout: 0.1
  fc_nlayers: 0
  fc_units: 1024

learning_config:
  augmentations: null

  dataset_config:
    train_paths:
      - sm_train.tsv
    eval_paths:
      - sm_dev.tsv
    test_paths:
      - sm_test.tsv
    tfrecords_dir: null

  optimizer_config:
    class_name: adam
    config:
      learning_rate: 0.0001

  running_config:
    batch_size: 4
    num_epochs: 20
    accumulation_steps: 8
    outdir: /deepspeech2
    log_interval_steps: 400
    save_interval_steps: 400
    eval_interval_steps: 800
